# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
target 'OCReduxDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OcReduxDemo
  pod 'YYKit'        , '1.0.9'
  pod 'ReactiveCocoa', '2.5.0'

end
